<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoTrader.Core\AlgoTrader.Core.csproj" />
    <ProjectReference Include="..\AlgoTrader.MarketData\AlgoTrader.MarketData.csproj" />
    <ProjectReference Include="..\AlgoTrader.Strategies\AlgoTrader.Strategies.csproj" />
    <ProjectReference Include="..\AlgoTrader.Trading\AlgoTrader.Trading.csproj" />
  </ItemGroup>

</Project>
